### ISSUE TITLE
[hedgedoc] SAML authentication requires a certificate mounted in container

### ISSUE THREAD

**Issue by quercus-carsten** [adfinis/helm-charts#1042]
**Is your feature request related to a problem? Please describe.**
Configuration of SAML authentication requires a certificate file present in the container with a path given in
env variable "CMD_SAML_IDPCERT".

**Describe the solution you'd like**
With extraVolumes and extraVolumeMounts one could provide the certificate using the "existingSecret".
Alternatively I found extraSecretMounts might be a more focused solution.

**Describe alternatives you've considered**
Unfortunately the documentation gives no alternative like simply putting the content of the certificate of the IDP into
an env variable. Using OIDC is no alternative.

**Affected chart**
hedgedoc

**Comment by gianklug** [comment]
Hey, thanks for reporting, I will update the helm chart later.

**Comment by gianklug** [comment]
@quercus-carsten `extraSecretMounts` has been implemented in #1044 and is available in chart version `0.2.0` :tada:

**Comment by quercus-carsten** [comment]
Thanks a lot @gianklug , just gave it a try and works like a charm! :)
