### ISSUE TITLE
Version v1.15.0-beta.1 of certManager is available!

### ISSUE THREAD

**Issue by eyenx** [adfinis/helm-charts#1240]
Hi!<br/></br>There is a new version available for certManager!<br/><br/>current targetRevision set: `1.13.2`<br/>new version available: `v1.15.0-beta.1`<br/><br/>Please consider updating the `targetRevision` with a PR in this file [values.yaml](https://github.com/adfinis/helm-charts/tree/master/charts/infra-apps/values.yaml)<br/><br/>Thanks.

**Comment by eyenx** [comment]
I'd say go for 1.15 if stable or update to 1.14 at least

**Comment by hairmare** [comment]
i did 1.14 a few weeks ago:
* https://github.com/adfinis/helm-charts/pull/1227
