### ISSUE TITLE
Version 6.6.0 of loki is available!

### ISSUE THREAD

**Issue by eyenx** [adfinis/helm-charts#1250]
Hi!<br/></br>There is a new version available for loki!<br/><br/>current targetRevision set: `5.41.4`<br/>new version available: `6.6.0`<br/><br/>Please consider updating the `targetRevision` with a PR in this file [values.yaml](https://github.com/adfinis/helm-charts/tree/master/charts/logging-apps/values.yaml)<br/><br/>Thanks.

**Comment by hairmare** [comment]
Does this update what happened here https://github.com/adfinis/helm-charts/pull/1234?
