### ISSUE TITLE
Version 6.15.5 of promtail is available!

### ISSUE THREAD

**Issue by eyenx** [adfinis/helm-charts#1251]
Hi!<br/></br>There is a new version available for promtail!<br/><br/>current targetRevision set: `6.15.3`<br/>new version available: `6.15.5`<br/><br/>Please consider updating the `targetRevision` with a PR in this file [values.yaml](https://github.com/adfinis/helm-charts/tree/master/charts/logging-apps/values.yaml)<br/><br/>Thanks.

**Comment by hairmare** [comment]
Fixed in #1234
