### ISSUE TITLE
[keycloak-operator] Disable operator templates

### ISSUE THREAD

**Issue by gwydionmv** [adfinis/helm-charts#1270]
**Is your feature request related to a problem? Please describe.**
As this chart generates the files for both the Operator and the Keycloak itself, it'd be a great feature to be able to disable one or the other to increase flexibility.

**Describe the solution you'd like**
Same as we have now `{{- if .Values.keycloak.enabled }}`, we could include something like `{{- if .Values.operator.enabled }}` in every operator template (deployment, service...).

**Additional context**
In our company, we want to have different projects, one for deploying the operator and another one for deploying Keycloak.

**Comment by hairmare** [comment]
Hi @gwydionmv 

Thanks for the feedback. I think this is a reasonable change. Would you be ready to prepare a PR?
