### ISSUE TITLE
Adfinis Theme for charts.adfinis.com

### ISSUE THREAD

**Issue by hairmare** [adfinis/helm-charts#41]
**Is your feature request related to a problem? Please describe.**
It doesn't look like our CI.

**Describe the solution you'd like**
It should look like our CI.

**Describe alternatives you've considered**
Not our CI.

**Affected chart**
The GitHub pages thing at https://charts.adfinis.com

**Additional context**
Nope

**TODOs**
* [ ] Adfinis GitHub Pages Theme ([adfinis-sygroup/jekyll-theme-adfinis](https://github.com/adfinis-sygroup/jekyll-theme-adfinis))

**Comment by gianklug** [comment]
Done in #968
