### ISSUE TITLE
Version 5.5.0 of fluentd is available!

### ISSUE THREAD

**Issue by eyenx** [adfinis/helm-charts#797]
Hi!<br/></br>There is a new version available for fluentd!<br/><br/>current targetRevision set: `5.1.*`<br/>new version available: `5.5.0`<br/><br/>Please consider updating the `targetRevision` with a PR in this file [values.yaml](https://github.com/adfinis/helm-charts/tree/master/charts/logging-apps/values.yaml)<br/><br/>Thanks.

**Comment by isantospardo** [comment]
Closing as https://github.com/adfinis/helm-charts/pull/855 is merged already
